# Development override for docker-compose.yml
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # PostgreSQL Database (Development)
  postgres:
    container_name: nextbrain-postgres-dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./nextBrain-back/prisma/init.sql:/docker-entrypoint-initdb.d/

  # Backend API (Development)
  backend:
    build:
      context: ./nextBrain-back
      dockerfile: Dockerfile.dev
    container_name: nextbrain-backend-dev
    environment:
      NODE_ENV: development
      JWT_SECRET: dev_jwt_secret_key
      JWT_REFRESH_SECRET: dev_jwt_refresh_secret_key
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    volumes:
      - ./nextBrain-back:/app
      - /app/node_modules
      - ./nextBrain-back/uploads:/app/uploads
    command: >
      sh -c "npm install &&
             npx prisma generate &&
             npx prisma migrate deploy &&
             npm run start:dev"

  # Frontend (Development)
  frontend:
    build:
      context: ./next-ora
      dockerfile: Dockerfile.dev
    container_name: nextbrain-frontend-dev
    volumes:
      - ./next-ora:/app
      - /app/node_modules

volumes:
  postgres_dev_data:
