services:
  postgres:
    image: postgres:15-alpine
    container_name: nextbrain-postgres
    environment:
      POSTGRES_USER: nextbrain
      POSTGRES_PASSWORD: nextbrain123
      POSTGRES_DB: nextbrain
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./nextBrain-back/prisma/init.sql:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - nextbrain-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextbrain -d nextbrain"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./nextBrain-back
      dockerfile: Dockerfile
    container_name: nextbrain-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://nextbrain:nextbrain123@postgres:5432/nextbrain?schema=public
      JWT_SECRET: your_jwt_secret_key_change_in_production
      JWT_REFRESH_SECRET: your_jwt_refresh_secret_key_change_in_production
      BACKEND_URL: http://10.9.21.110:3000
      FRONTEND_URL: http://10.9.21.110:8080
      BASE_URL: http://10.9.21.110:3000
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USER: gaithrouahi@gmail.com
      MAIL_PASS: "xubl hogw wrdx uwgi"
      MAIL_FROM_NAME: NextBrain
      GEMINI_API_KEY: ${GEMINI_API_KEY:-AIzaSyDQJwyVvyvAmuSLpl4bRgSRieuIVsOjsuQ}
      LLAMA_API_URL: ${LLAMA_API_URL:-http://10.9.21.110:11434/api/chat}
      VECTOR_DB_URL: http://qdrant:6333
      RAG_SERVICE_URL: http://10.9.21.110:8001
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    networks:
      - nextbrain-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nextBrain-back/uploads:/app/uploads
    command: >
      sh -c "npx prisma migrate deploy &&\
              npx prisma db seed &&\
              npm run start:prod"

  frontend:
    build:
      context: ./next-ora-new
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://10.9.21.110:3000/api
    container_name: nextbrain-frontend
    environment:
      VITE_API_URL: http://10.9.21.110:3000/api
      VITE_APP_NAME: NextOra
      VITE_APP_VERSION: 1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - nextbrain-network

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/amd64
    container_name: nextbrain-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - nextbrain-network
    healthcheck:
      test: ["CMD", "bash", "-c", "exec 3<>/dev/tcp/127.0.0.1/6333 && echo -e 'GET /readyz HTTP/1.1\\r\\nHost: 10.9.21.110\\r\\nConnection: close\\r\\n\\r\\n' >&3 && grep -q 'HTTP/1.1 200' <&3"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  rag-service:
    build:
      context: ./rag-service
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: nextbrain-rag-service
    environment:
      VECTOR_DB: qdrant
      VECTOR_DB_URL: http://qdrant:6333
      UPLOAD_DIR: /data/uploads
      GEMINI_API_KEY: ${GEMINI_API_KEY:-}
    ports:
      - "8001:8001"
    depends_on:
      - qdrant
    networks:
      - nextbrain-network
    volumes:
      - ./nextBrain-back/uploads:/data/uploads
      - qdrant_data:/data/qdrant

networks:
  nextbrain-network:
    driver: bridge

volumes:
  postgres_data:
  qdrant_data:
  rag_qdrant_data:
