name: Auto Update Submodules

on:
  schedule:
    - cron: '0/1 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:     # Allow manual trigger

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update submodules" || echo "No changes to commit"
          git push
